### ISSUE TITLE
[1.16.5] Crash on breaking XReliquary:InterdictionTorch after update to 2.0.12 from 2.0.11

### ISSUE THREAD

**Issue by drakray** [McJtyMods/FxControl#30]
https://pastebin.com/kJcW5MVk

Got crash as I broke the torch first thing after entering my solo game

**Comment by drakray** [comment]
got it even after reverting to 2.0.11, I'm trying something(moving before breaking the torch)

EDIT: same with breaking another block, and after moving; trying reverting InControl from 5.2.0 to 5.1.9

**Comment by drakray** [comment]
Reverting InControl from 5.2.0 to 5.1.9 fixed it, will now try FxControl 2.0.12 with InControl 5.1.9

EDIT: it's working by reverting InControl from 5.2.0 to 5.1.9

**Comment by LaughingLeader** [comment]
I have a similar crash with GenericRuleEvaluator after the same InControl update, except for an EffectRule instead of a HarvestRule.
[crash-2021-08-13_15.48.10-server.txt](https://github.com/McJtyMods/FxControl/files/6985129/crash-2021-08-13_15.48.10-server.txt)

Additionally I tested this on a fresh instance with minimal mods, and didn't get the crash with the same FxControl rules, so it may be some sort of mod incompatibility.

**Comment by McJty** [comment]
Updating FxControl should fix this
